Repository ittovate/demo-otp-service, pull requests merged in 2024-09, with the labels that each got.

#8 Update Checkstyle Rules
  config/checkstyle/checkstyle_changelog.md
  config/checkstyle/sun_checks_custom.xml
  src/main/java/com/ittovative/otpservice/aspect/LoggingAspect.java
  src/main/java/com/ittovative/otpservice/config/RedisConfig.java
  src/main/java/com/ittovative/otpservice/controller/OtpController.java
  src/main/java/com/ittovative/otpservice/exception/GeneralExceptionHandler.java
  src/main/java/com/ittovative/otpservice/service/InMemoryVerificationService.java
  src/main/java/com/ittovative/otpservice/service/RedisVerificationService.java
  src/main/java/com/ittovative/otpservice/service/SmsService.java
  src/main/java/com/ittovative/otpservice/service/TwilioSenderService.java
  src/main/java/com/ittovative/otpservice/util/ApiResponse.java
Labels: enhancement

#9 Restructure README.md
  README.md
Labels: documentation

#10 Fix Numbering Typo in README
  README.md
Labels: documentation

#11 Move All Docs Files to `docs` Directory
  docs/README.md
  docs/checkstyle_changelog.md
  docs/images/endpoint-example-1.png
  docs/images/endpoint-example-2.png
  docs/images/endpoint-example-3.png
  docs/images/endpoint-example-4.png
  docs/images/swagger1.png
  docs/usage.md
Labels: documentation, refactor

#12 Refactor Logging
  src/main/java/com/ittovative/otpservice/aspect/LoggingAspect.java
  src/main/java/com/ittovative/otpservice/util/AspectUtil.java
Labels: refactor

#14 Refactor Swagger to be Separate From Controller
  src/main/java/com/ittovative/otpservice/OtpServiceApplication.java
  src/main/java/com/ittovative/otpservice/config/SwaggerConfig.java
  src/main/java/com/ittovative/otpservice/constant/ApiResponseConstant.java
  src/main/java/com/ittovative/otpservice/constant/HttpConstant.java
  src/main/java/com/ittovative/otpservice/constant/SwaggerConstant.java
  src/main/java/com/ittovative/otpservice/controller/OtpController.java
  src/main/java/com/ittovative/otpservice/dto/OtpRequestDto.java
  src/main/java/com/ittovative/otpservice/dto/VerifyOtpRequestDto.java
  src/main/java/com/ittovative/otpservice/dto/VerifyTokenRequestDto.java
  src/main/java/com/ittovative/otpservice/exception/GeneralExceptionHandler.java
  src/main/java/com/ittovative/otpservice/service/RedisVerificationService.java
  src/main/java/com/ittovative/otpservice/service/SmsService.java
  src/main/java/com/ittovative/otpservice/util/ApiResponse.java
Labels: documentation, refactor

#15 Do Chores
  docs/README.md
  docs/usage.md
  src/main/java/com/ittovative/otpservice/constant/RedisConstant.java
  src/main/java/com/ittovative/otpservice/constant/SwaggerConstant.java
  src/main/java/com/ittovative/otpservice/exception/GeneralExceptionHandler.java
  src/main/java/com/ittovative/otpservice/model/VerificationOtp.java
  src/main/java/com/ittovative/otpservice/service/RedisVerificationService.java
Labels: documentation, refactor

#16 Refactor `RedisTest`
  src/main/java/com/ittovative/otpservice/model/VerificationOtp.java
  src/main/java/com/ittovative/otpservice/service/SmsService.java
  src/test/java/com/ittovative/otpservice/OtpServiceApplicationTests.java
  src/test/java/com/ittovative/otpservice/RedisTest.java
  src/test/java/com/ittovative/otpservice/service/SmsServiceTest.java
Labels: refactor

#17 Refactor and Add CI Workflow
  .github/workflows/ci.yml
  config/.pre-commit-config.yaml
  docs/README.md
  src/main/java/com/ittovative/otpservice/aspect/LoggingAspect.java
  src/main/java/com/ittovative/otpservice/config/CollectionsConfig.java
  src/main/java/com/ittovative/otpservice/config/RedisConfig.java
  src/main/java/com/ittovative/otpservice/config/SwaggerConfig.java
  src/main/java/com/ittovative/otpservice/config/TwilioConfig.java
  src/main/java/com/ittovative/otpservice/config/VerificationConfig.java
  src/main/java/com/ittovative/otpservice/constant/ApiResponseConstant.java
  src/main/java/com/ittovative/otpservice/constant/AspectConstant.java
  src/main/java/com/ittovative/otpservice/constant/ExceptionConstant.java
  src/main/java/com/ittovative/otpservice/constant/HttpConstant.java
  src/main/java/com/ittovative/otpservice/constant/RedisConstant.java
  src/main/java/com/ittovative/otpservice/constant/SwaggerConstant.java
  src/main/java/com/ittovative/otpservice/controller/OtpController.java
  src/main/java/com/ittovative/otpservice/dto/OtpRequestDto.java
  src/main/java/com/ittovative/otpservice/dto/TokenDto.java
  src/main/java/com/ittovative/otpservice/exception/GeneralExceptionHandler.java
  src/main/java/com/ittovative/otpservice/model/Token.java
  src/main/java/com/ittovative/otpservice/service/InMemoryVerificationService.java
  src/main/java/com/ittovative/otpservice/service/OtpService.java
  src/main/java/com/ittovative/otpservice/service/RedisVerificationService.java
  src/main/java/com/ittovative/otpservice/service/SmsService.java
  src/main/java/com/ittovative/otpservice/util/AspectUtil.java
  src/test/java/com/ittovative/otpservice/service/OtpServiceTest.java
Labels: enhancement, refactor

#18 Fix Workflow by Adding the Secrets
  .github/workflows/ci.yml
Labels: bug

#19 Do chores
  docs/README.md
  src/main/java/com/ittovative/otpservice/service/OtpService.java
  src/main/java/com/ittovative/otpservice/service/RedisVerificationService.java
  src/main/java/com/ittovative/otpservice/service/SmsService.java
  src/main/java/com/ittovative/otpservice/service/TwilioSenderService.java
  src/main/java/com/ittovative/otpservice/service/VerificationService.java
Labels: refactor

#20 Fix test check failing on pushing to master
  .github/workflows/ci.yml
Labels: bug

#21 Refactor API Response and Other Classes
  src/main/java/com/ittovative/otpservice/config/SwaggerConfig.java
  src/main/java/com/ittovative/otpservice/constant/APIResponseConstant.java
  src/main/java/com/ittovative/otpservice/constant/HTTPConstant.java
  src/main/java/com/ittovative/otpservice/controller/OTPController.java
  src/main/java/com/ittovative/otpservice/controller/OtpController.java
  src/main/java/com/ittovative/otpservice/dto/OTPRequestDTO.java
  src/main/java/com/ittovative/otpservice/dto/TokenDTO.java
  src/main/java/com/ittovative/otpservice/exception/GeneralExceptionHandler.java
  src/main/java/com/ittovative/otpservice/log/LoggingAspect.java
  src/main/java/com/ittovative/otpservice/service/OTPService.java
  src/main/java/com/ittovative/otpservice/util/APIResponse.java
  src/main/java/com/ittovative/otpservice/util/ApiResponse.java
  src/main/java/com/ittovative/otpservice/util/ResponseUtil.java
  src/test/java/com/ittovative/otpservice/OTPServiceApplicationTests.java
  src/test/java/com/ittovative/otpservice/service/OTPServiceTest.java
Labels: refactor

#23 Refactor `OTPService` with testing and JavaDocs
  config/.pre-commit-config.yaml
  pom.xml
  src/main/java/com/ittovative/otpservice/OtpServiceApplication.java
  src/main/java/com/ittovative/otpservice/config/RedisConfig.java
  src/main/java/com/ittovative/otpservice/config/TwilioConfig.java
  src/main/java/com/ittovative/otpservice/constant/APIResponseConstant.java
  src/main/java/com/ittovative/otpservice/constant/AspectConstant.java
  src/main/java/com/ittovative/otpservice/constant/ExceptionConstant.java
  src/main/java/com/ittovative/otpservice/constant/HTTPConstant.java
  src/main/java/com/ittovative/otpservice/constant/RedisConstant.java
  src/main/java/com/ittovative/otpservice/constant/ServiceConstant.java
  src/main/java/com/ittovative/otpservice/constant/SwaggerConstant.java
  src/main/java/com/ittovative/otpservice/controller/OTPController.java
  src/main/java/com/ittovative/otpservice/dto/OTPRequestDTO.java
  src/main/java/com/ittovative/otpservice/dto/TokenDTO.java
  src/main/java/com/ittovative/otpservice/exception/GeneralExceptionHandler.java
  src/main/java/com/ittovative/otpservice/log/LoggingAspect.java
  src/main/java/com/ittovative/otpservice/model/Token.java
  src/main/java/com/ittovative/otpservice/service/OTPService.java
  src/main/java/com/ittovative/otpservice/service/TwilioSenderService.java
  src/main/java/com/ittovative/otpservice/service/VerificationService.java
  src/main/java/com/ittovative/otpservice/util/APIResponseUtil.java
  src/main/java/com/ittovative/otpservice/util/AspectUtil.java
  src/main/java/com/ittovative/otpservice/util/ResponseUtil.java
  src/test/java/com/ittovative/otpservice/constant/OtpServiceTestConstant.java
  src/test/java/com/ittovative/otpservice/service/OTPServiceTest.java
Labels: refactor
